### ISSUE TITLE
update the link of the contact us section to redirect the user to the correct webpage

### ISSUE THREAD

**Issue by github4maninder** [Microsoft-LSA-Nexus-Chapter/Nexus-Chapter-Website#15]
I would like to update the link of the contact us section in the footer -
currently when you click the section it redirect the user to the about page but with update the user will be redirected to 
 "https://mlsa-nexus-chapter.netlify.app/contact" section.
 
 Thanks! Assign me the issue @Shinjan-saha

![before edit](https://github.com/user-attachments/assets/648a1781-5b6d-4044-a3d2-7c5d64579cce)

**Comment by komal-agarwal5** [comment]
@github4maninder We respect your keen observation for finding this out but we won't be able to assign this issue to you since currently, we are not accepting contributions involving just a single change like this in order to comply with the guidelines of our project.
You can work on any other issue.Thank you for your interest.
